<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

<img src = "https://github.com/Jangrae/img/blob/master/mobile2.png?raw=true" width=800 align="left"/>

# 실습 내용

- 다양한 알고리즘으로 모델을 만들고 성능을 예측합니다.
- 성능이 좋을 것으로 판단된 모델의 성능을 튜닝합니다.
- 튜닝된 모델의 성능을 평가합니다.

# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [2]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

In [3]:
# 데이터 불러오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/mobile_cust_churn.csv'
data = pd.read_csv(path)
data['CHURN'] = data['CHURN'].map({'STAY':0, 'LEAVE': 1})

# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

In [5]:
# 데이터 살펴보기
data.head()

id  COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0   1        0   31953        0         6  313378            161   
1   2        1   36147        0        13  800586            244   
2   3        1   27273      230         0  305049            201   
3   4        0  120070       38        33  788235            780   
4   5        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION REPORTED_SATISFACTION  \
0                            0                      4                 unsat   
1                            0                      6                 unsat   
2                           16                     15                 unsat   
3                            3                      2                 unsat   
4                           21                      1            very_unsat   

  REPORTED_USAGE_LEVEL CONSIDERING_CHANGE_OF_PLAN  CHURN  
0               little                         no      0  
1               little                considering      0  
2          very_little                    perhaps      0  
3            very_high                considering      1  
4               little              never_thought      0

**데이터 설명**

- COLLEGE: 대학 졸업여부
- INCOME: 연수입
- OVERAGE: 월평균 초과사용 시간(분)
- LEFTOVER: 월평균 잔여시간비율(%)
- HOUSE: 집값
- HANDSET_PRICE: 스마트폰 가격
- OVER_15MINS_CALLS_PER_MONTH: 월평균 장기통화(15분이상) 횟수
- AVERAGE_CALL_DURATION: 평균 통화 시간
- REPORTED_SATISFACTION: 만족도 설문조사 결과
- REPORTED_USAGE_LEVEL: 사용도 자가진단 결과
- CONSIDERING_CHANGE_OF_PLAN: 향후 변경계획 설문조사 결과
- CHURN: 이탈(번호이동) 여부

In [8]:
# 기술통계 확인
data.describe()

id       COLLEGE         INCOME       OVERAGE      LEFTOVER  \
count  20000.000000  20000.000000   20000.000000  20000.000000  20000.000000   
mean   10000.500000      0.502400   80281.447750     85.979550     23.898650   
std     5773.647028      0.500007   41680.586319     85.992324     26.816645   
min        1.000000      0.000000   20007.000000     -2.000000      0.000000   
25%     5000.750000      0.000000   42217.000000      0.000000      0.000000   
50%    10000.500000      1.000000   75366.500000     59.000000     14.000000   
75%    15000.250000      1.000000  115881.750000    179.000000     41.000000   
max    20000.000000      1.000000  159983.000000    335.000000     89.000000   

               HOUSE  HANDSET_PRICE  OVER_15MINS_CALLS_PER_MONTH  \
count   20000.000000   20000.000000                 20000.000000   
mean   493155.264250     389.615100                     8.000700   
std    252407.884692     213.820682                     8.925418   
min    150002.000000     130.000000                     0.000000   
25%    263714.250000     219.000000                     1.000000   
50%    452259.500000     326.000000                     4.000000   
75%    702378.000000     533.250000                    15.000000   
max    999996.000000     899.000000                    29.000000   

       AVERAGE_CALL_DURATION         CHURN  
count           20000.000000  20000.000000  
mean                6.002250      0.492600  
std                 4.402558      0.499958  
min                 1.000000      0.000000  
25%                 2.000000      0.000000  
50%                 5.000000      0.000000  
75%                10.000000      1.000000  
max                15.000000      1.000000

# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) 변수 제거**

In [14]:
# 제거 대상: id
drop_cols = ['id']

# 변수 제거
data.drop(drop_cols, axis= 1, inplace=True)

# 확인
data.head()

COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0        0   31953        0         6  313378            161   
1        1   36147        0        13  800586            244   
2        1   27273      230         0  305049            201   
3        0  120070       38        33  788235            780   
4        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION REPORTED_SATISFACTION  \
0                            0                      4                 unsat   
1                            0                      6                 unsat   
2                           16                     15                 unsat   
3                            3                      2                 unsat   
4                           21                      1            very_unsat   

  REPORTED_USAGE_LEVEL CONSIDERING_CHANGE_OF_PLAN  CHURN  
0               little                         no      0  
1               little                considering      0  
2          very_little                    perhaps      0  
3            very_high                considering      1  
4               little              never_thought      0

**2) x, y 분리**

In [22]:
# Target 설정
target = 'CHURN'

# 데이터 분리
x=data.drop(target, axis= 1)
y=data[target]


**3) 가변수화**

In [24]:
# 가변수화 대상: REPORTED_SATISFACTION, REPORTED_USAGE_LEVEL, CONSIDERING_CHANGE_OF_PLAN
dumm_cols =['REPORTED_SATISFACTION','REPORTED_USAGE_LEVEL','CONSIDERING_CHANGE_OF_PLAN']

# 가변수화
x=pd.get_dummies(x,dumm_cols,drop_first=True,dtype=int)

# 확인
x.head()

COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0        0   31953        0         6  313378            161   
1        1   36147        0        13  800586            244   
2        1   27273      230         0  305049            201   
3        0  120070       38        33  788235            780   
4        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION  \
0                            0                      4   
1                            0                      6   
2                           16                     15   
3                            3                      2   
4                           21                      1   

   REPORTED_SATISFACTION_sat  REPORTED_SATISFACTION_unsat  \
0                          0                            1   
1                          0                            1   
2                          0                            1   
3                          0                            1   
4                          0                            0   

   REPORTED_SATISFACTION_very_sat  REPORTED_SATISFACTION_very_unsat  \
0                               0                                 0   
1                               0                                 0   
2                               0                                 0   
3                               0                                 0   
4                               0                                 1   

   REPORTED_USAGE_LEVEL_high  REPORTED_USAGE_LEVEL_little  \
0                          0                            1   
1                          0                            1   
2                          0                            0   
3                          0                            0   
4                          0                            1   

   REPORTED_USAGE_LEVEL_very_high  REPORTED_USAGE_LEVEL_very_little  \
0                               0                                 0   
1                               0                                 0   
2                               0                                 1   
3                               1                                 0   
4                               0                                 0   

   CONSIDERING_CHANGE_OF_PLAN_considering  \
0                                       0   
1                                       1   
2                                       0   
3                                       1   
4                                       0   

   CONSIDERING_CHANGE_OF_PLAN_never_thought  CONSIDERING_CHANGE_OF_PLAN_no  \
0                                         0                              1   
1                                         0                              0   
2                                         0                              0   
3                                         0                              0   
4                                         1                              0   

   CONSIDERING_CHANGE_OF_PLAN_perhaps  
0                                   0  
1                                   0  
2                                   1  
3                                   0  
4                                   0

**4) 학습용, 평가용 데이터 분리**

In [26]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split

# 7:3으로 분리
x_train , x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=1)

**5) 정규화**

In [28]:
# 모듈 불러오기
from sklearn.preprocessing import MinMaxScaler

# 정규화
scaler = MinMaxScaler()
x_train_s= scaler.fit_transform(x_train)
x_test_s = scaler.transform(x_test)



# 4.성능 예측

- 여러 알고리즘으로 모델을 만들고 K-Fold CV로 성능을 예측합니다.
- 하이퍼파라미터를 설정하지 않고 진행합니다.
- 각 모델의 성능 정보를 수집해 마지막에 비교합니다.

In [30]:
# xgboost 설치
# !pip install xgboost

In [32]:
# lightgbm 설치
# !pip install lightgbm

- 이후 사용할 함수를 모두 불러옵니다.

In [35]:
# 불러오기
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

**1) KNN**

- KNN 알고리즘으로 모델링하고 K-Fold CV로 성능을 검증합니다.

In [43]:
# 선언하기
model = KNeighborsClassifier()

In [45]:
# 성능예측
cv_score =cross_val_score(model,x_train_s, y_train ,cv=5)

In [46]:
# 결과확인
print(cv_score)
print('mean:',cv_score.mean())

[0.58571429 0.60035714 0.57785714 0.60321429 0.59785714]
mean: 0.5930000000000001


In [49]:
# 결과수집
result = {}
result['KNN'] = cv_score.mean()

**2) Decision Tree**

- Decision Tree 알고리즘으로 모델링하고 K-Fold CV로 성능을 검증합니다.

In [51]:
# 선언하기
model = DecisionTreeClassifier()

In [53]:
# 성능예측
cv_score = cross_val_score(model , x_train , y_train , cv=5)

In [55]:
# 결과확인
print(cv_score)
print('mean:',cv_score.mean())

[0.61857143 0.61928571 0.61428571 0.6075     0.63142857]
mean: 0.6182142857142857


In [57]:
# 결과수집
result['Decision Tree'] = cv_score.mean()

**3) Logistic Regression**

- Logistic Regression 알고리즘으로 모델링하고 K-Fold CV로 성능을 검증합니다.

In [59]:
# 선언하기
model = LogisticRegression()

In [61]:
# 성능예측

cv_score = cross_val_score(model , x_train , y_train , cv=5)

In [63]:
# 결과확인

print(cv_score)
print('mean:',cv_score.mean())

[0.62678571 0.63642857 0.62535714 0.64714286 0.63964286]
mean: 0.6350714285714286


In [65]:
# 결과수집
result['Logistic Regression'] = cv_score.mean()

**4) Random Forest**

- Random Forest 알고리즘으로 모델링하고 K-Fold CV로 성능을 검증합니다.

In [67]:
# 선언하기
model = RandomForestClassifier()

In [69]:
# 성능예측
cv_score = cross_val_score(model, x_train , y_train, cv=5)

In [70]:
# 결과확인

print(cv_score)
print('mean:',cv_score.mean())

[0.67964286 0.69678571 0.68035714 0.69285714 0.68928571]
mean: 0.6877857142857142


In [71]:
# 결과수집
result['Random Forest'] = cv_score.mean()

**5) XGBoost**

- XGBoost 알고리즘으로 모델링하고 K-Fold CV로 성능을 검증합니다.

In [75]:
# 선언하기
model = XGBClassifier()

In [77]:
# 성능예측
cv_score = cross_val_score(model, x_train, y_train, cv=5)

In [79]:
# 결과확인

print(cv_score)
print('mean:',cv_score.mean())

[0.67857143 0.69607143 0.67892857 0.69285714 0.68678571]
mean: 0.6866428571428573


In [81]:
# 결과수집
result['XGBoost'] = cv_score.mean()

**6) LightGBM**

- LightGBM 알고리즘으로 모델링하고 K-Fold CV로 성능을 검증합니다.

In [86]:
# 선언하기
model = LGBMClassifier()

In [95]:
# 성능예측
cv_score=cross_val_score(model,x_train,y_train, cv=5)

[LightGBM] [Info] Number of positive: 5534, number of negative: 5666
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000777 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1139
[LightGBM] [Info] Number of data points in the train set: 11200, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.494107 -> initscore=-0.023573
[LightGBM] [Info] Start training from score -0.023573
[LightGBM] [Info] Number of positive: 5534, number of negative: 5666
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000627 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1136
[LightGBM] [Info] Number of data points in the train set: 11200, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.494107 -> initscore=-0.023573
[LightGBM] [Info] Start training from score -0.023573
[LightGBM] [Info

In [96]:
# 결과확인

print(cv_score)
print('mean:',cv_score.mean())

[0.68785714 0.71428571 0.68321429 0.6975     0.69821429]
mean: 0.6962142857142857


In [97]:
# 결과수집
result['LightGBM'] = cv_score.mean()

# 5.결과 확인

- 예측된 각 모델의 성능을 비교합니다.

In [102]:
# 성능 비교
print('=' * 40)
for m_name, score in result.items():
    print(m_name, score.round(3))
print('=' * 40)

KNN 0.593
Decision Tree 0.618
Logistic Regression 0.635
Random Forest 0.688
XGBoost 0.687
LightGBM 0.696


In [104]:
# 성능 시각화 비교
plt.barh(list(result), result.values())
plt.show()

# 6.성능 튜닝

- 위에서 성능이 가장 좋을 것으로 예측된 모델을 튜닝합니다.
- 본 실습에서는 LightGBM 모델 성능을 튜닝합니다.

In [111]:
# 기본 모델 선언
model= LGBMClassifier(verbose = -1)

# 파라미터 지정
  # max_depth: range(1, 21)
param = {'max_depth': range(1,21)}

# 모델 선언
model = GridSearchCV(model,
                     param,
                     cv=5,
                    scoring='accuracy')




In [113]:
# 학습하기(많은 시간이 소요될 수 있음)
model.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LGBMClassifier(verbose=-1),
             param_grid={'max_depth': range(1, 21)}, scoring='accuracy')

In [114]:
# 최적 파라미터, 예측 최고 성능
print(model.best_params_)
print(model.best_score_)


{'max_depth': 6}
0.6980000000000001


In [115]:
# 변수 중요도 시각화
plt.barh(list(x), model.best_estimator_.feature_importances_)
plt.show()



# 7.성능 평가

- 최적 파라미터로 학습된 모델에 대해 최종 성능 평가를 진행합니다.

In [117]:
# 예측하기
y_pred = model.predict(x_test)

In [118]:
# 성능평가
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1953 1112]
 [ 747 2188]]
              precision    recall  f1-score   support

           0       0.72      0.64      0.68      3065
           1       0.66      0.75      0.70      2935

    accuracy                           0.69      6000
   macro avg       0.69      0.69      0.69      6000
weighted avg       0.69      0.69      0.69      6000

